@echo off
echo Starting UK Mini App...

echo Installing frontend dependencies...
npm install

echo Installing backend dependencies...
pip install -r requirements.txt

echo Starting backend server...
start "Backend Server" cmd /k "python app.py"

echo Starting frontend development server...
start "Frontend Server" cmd /k "npm run dev"

echo.
echo UK Mini App is starting...
echo Frontend: http://localhost:3000
echo Backend: http://127.0.0.1:8000
echo.
echo Press any key to exit...
pause > nul 